# Nom du workflow
name: Cypress Tests

# Déclencheurs
on:
  # Lancement manuel possible
  workflow_dispatch:

jobs:
  signup-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code du repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Lancer Cypress (tests negotiation + critical)
      - name: Run Cypress negotiation critical tests
        run: npx cypress run --env TAGS="@negotiation and @critical"

      # 5️⃣ Upload des screenshots et vidéos Cypress
      # Très utile pour analyser les échecs
      - name: Upload Cypress artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
